// apps/web-react/src/components/layout/TwoColumnPanel.tsx
import { ReactNode } from 'react';
import { cn } from '@/lib/utils';

interface Props {
  left: ReactNode;
  right: ReactNode;
  leftClassName?: string;
  rightClassName?: string;
}

export function TwoColumnPanel({ left, right, leftClassName, rightClassName }: Props) {
  return (
    <div className="flex h-full w-full overflow-hidden">
      <div className={cn('overflow-y-auto border-r border-border', leftClassName ?? 'w-1/3')}>
        {left}
      </div>
      <div className={cn('flex-1 overflow-y-auto', rightClassName)}>
        {right}
      </div>
    </div>
  );
}

// apps/web/src/lib/components/layout/TwoColumnPanel.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils';

  let {
    left,
    right,
    leftClassName,
    rightClassName,
  }: {
    left?: Snippet;
    right?: Snippet;
    leftClassName?: string;
    rightClassName?: string;
  } = $props();
</script>

<div class="flex h-full w-full overflow-hidden">
  <div class={cn('overflow-y-auto border-r border-border', leftClassName ?? 'w-1/3')}>
    {@render left?.()}
  </div>
  <div class={cn('flex-1 overflow-y-auto', rightClassName)}>
    {@render right?.()}
  </div>
</div>
