// apps/web/src/lib/components/LayoutDocumentView.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { Artifact, InboundMessage } from '@multiplayer-base/shared-types';
  import { eventManager } from '$lib/services/EventManager';
  import { subscribeToModel, getModelSnapshot, mountChannel } from '$lib/services/documentModelStore';
  import type { DocModel } from '$lib/services/documentModelStore';
  import LayoutRenderer from './LayoutRenderer.svelte';

  let {
    doc,
    channelId: channelIdProp,
    viewHandler = 'defaultView',
  }: {
    doc?: Artifact;
    channelId?: string;
    viewHandler?: string;
  } = $props();

  let resolvedChannelId = $derived(channelIdProp ?? doc?.currentChannelId ?? '');

  function emit(type: string, payload: Record<string, unknown> = {}) {
    eventManager.publish(resolvedChannelId, {
      type,
      from: 'client' as const,
      to: 'server' as const,
      channel: resolvedChannelId,
      timestamp: new Date().toISOString(),
      ...payload,
    } as unknown as InboundMessage);
  }

  let model = $state<DocModel>({ layoutConfig: [], docState: { state: {}, temp: {} } });

  let unsub: (() => void) | null = null;

  function setup(channelId: string, vh: string) {
    unsub?.();
    model = getModelSnapshot(channelId, vh);
    unsub = subscribeToModel(channelId, vh, () => {
      model = getModelSnapshot(channelId, vh);
    });
    mountChannel(channelId, emit, vh);
  }

  $effect(() => {
    setup(resolvedChannelId, viewHandler);
  });

  onDestroy(() => unsub?.());
</script>

{#if model.layoutConfig.length === 0}
  <p class="doc-empty">Loading…</p>
{:else}
  <LayoutRenderer
    nodes={model.layoutConfig}
    state={model.docState as unknown as Record<string, unknown>}
    {emit}
  />
{/if}

// apps/web/src/app/components/LayoutDocumentView.tsx
import { useSyncExternalStore, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Artifact, InboundMessage } from '@agentic-client-server-base/shared-types';
import { eventManager } from '../services/EventManager';
import { LayoutRenderer } from '../../components/LayoutRenderer';
import { subscribeToModel, getModelSnapshot, mountChannel, onRedirect } from '../services/documentModelStore';

interface Props {
  doc?: Artifact;
  channelId?: string;
  viewHandler?: string;
}

export function LayoutDocumentView({ doc, channelId: channelIdProp, viewHandler = 'defaultView' }: Props) {
  const resolvedChannelId = channelIdProp ?? doc?.currentChannelId ?? '';

  const navigate = useNavigate();

  useEffect(() => {
    return onRedirect(resolvedChannelId, (url) => navigate(url));
  }, [resolvedChannelId, navigate]);

  const emit = useCallback((type: string, payload: Record<string, unknown> = {}) => {
    eventManager.publish(resolvedChannelId, {
      type,
      from: 'client' as const,
      to: 'server' as const,
      channel: resolvedChannelId,
      timestamp: new Date().toISOString(),
      ...payload,
    } as unknown as InboundMessage);
  }, [resolvedChannelId]);

  useEffect(() => {
    mountChannel(resolvedChannelId, emit, viewHandler);
  }, [resolvedChannelId, emit, viewHandler]);

  const model = useSyncExternalStore(
    useCallback((cb) => subscribeToModel(resolvedChannelId, viewHandler, cb), [resolvedChannelId, viewHandler]),
    useCallback(() => getModelSnapshot(resolvedChannelId, viewHandler), [resolvedChannelId, viewHandler])
  );

  if (model.layoutConfig.length === 0) {
    return <p className="doc-empty">Loading…</p>;
  }

  return (
    <LayoutRenderer
      nodes={model.layoutConfig}
      state={model.docState as unknown as Record<string, unknown>}
      emit={emit}
    />
  );
}
