// apps/web/src/lib/components/PageHeader.svelte
<script lang="ts">
  import { authStore } from '$lib/stores/auth';
  import { goto } from '$app/navigation';

  let { title }: { title: string } = $props();

  function handleLogout() {
    authStore.logout();
    goto('/login');
  }
</script>

<header class="page-header">
  <h1>{title}</h1>
  <nav>
    <span>{$authStore.user?.email}</span>
    <a href="/dashboard" class="btn-secondary">Dashboard</a>
    <a href="/settings" class="btn-secondary">Settings</a>
    <button onclick={handleLogout} class="btn-secondary">Logout</button>
  </nav>
</header>

// apps/web/src/app/components/PageHeader.tsx
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

interface PageHeaderProps {
  title: string;
}

export function PageHeader({ title }: PageHeaderProps) {
  const { user, logout } = useAuth();

  return (
    <header className="page-header">
      <h1>{title}</h1>
      <nav>
        <span>{user?.email}</span>
        <Link to="/dashboard" className="btn-secondary">Dashboard</Link>
        <Link to="/settings" className="btn-secondary">Settings</Link>
        <button onClick={logout} className="btn-secondary">Logout</button>
      </nav>
    </header>
  );
}
