// apps/web/src/lib/components/layout/ChatInput.svelte
<script lang="ts">
  let { onAddText }: { onAddText?: (payload: { text: string }) => void } = $props();

  let text = $state('');

  function submit() {
    const trimmed = text.trim();
    if (!trimmed || !onAddText) return;
    onAddText({ text: trimmed });
    text = '';
  }

  function handleSubmit(e: Event) {
    e.preventDefault();
    submit();
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      submit();
    }
  }
</script>

<form class="chat-input" onsubmit={handleSubmit}>
  <textarea
    class="chat-input__field"
    placeholder="Type a message…"
    bind:value={text}
    onkeydown={handleKeydown}
    rows={1}
  ></textarea>
  <button type="submit" class="btn-primary" disabled={!text.trim()}>Send</button>
</form>

// apps/web-react/src/components/layout/ChatInput.tsx
import { useState, FormEvent, KeyboardEvent } from 'react';

interface Props {
  onAddText?: (payload: { text: string }) => void;
  [key: string]: unknown;
}

export function ChatInput({ onAddText }: Props) {
  const [text, setText] = useState('');

  const submit = () => {
    const trimmed = text.trim();
    if (!trimmed || !onAddText) return;
    onAddText({ text: trimmed });
    setText('');
  };

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    submit();
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      submit();
    }
  };

  return (
    <form className="chat-input" onSubmit={handleSubmit}>
      <textarea
        className="chat-input__field"
        placeholder="Type a message…"
        value={text}
        onChange={(e) => setText(e.target.value)}
        onKeyDown={handleKeyDown}
        rows={1}
      />
      <button type="submit" className="btn-primary" disabled={!text.trim()}>
        Send
      </button>
    </form>
  );
}
