// apps/web/src/lib/components/layout/DocumentList.svelte
<script lang="ts">
  import type { ArtifactSummary } from '@multiplayer-base/shared-types';

  let {
    items = [],
    onSelect,
  }: {
    items?: ArtifactSummary[];
    onSelect?: (payload: { documentId: string }) => void;
  } = $props();
</script>

{#if items.length === 0}
  <p class="doc-empty">No documents yet.</p>
{:else}
  <ul class="doc-list">
    {#each items as doc (doc._id)}
      <li
        class="doc-list-item"
        onclick={() => onSelect?.({ documentId: doc._id })}
        tabindex="0"
        onkeydown={(e) => e.key === 'Enter' && onSelect?.({ documentId: doc._id })}
      >
        <span class="doc-name">{doc.name}</span>
        <span class="doc-type">{doc.type}</span>
      </li>
    {/each}
  </ul>
{/if}

// apps/web/src/components/layout/DocumentList.tsx
import { ArtifactSummary } from '@multiplayer-base/shared-types';

interface Props {
  items?: ArtifactSummary[];
  onSelect?: (payload: { documentId: string }) => void;
  [key: string]: unknown;
}

export function DocumentList({ items = [], onSelect }: Props) {
  if (items.length === 0) {
    return <p className="doc-empty">No documents yet.</p>;
  }

  return (
    <ul className="doc-list">
      {items.map((doc) => (
        <li key={doc._id} className="doc-list-item">
          <span className="doc-name">
            {doc.name} ({doc.type}, {new Date(doc.createdAt).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })})
            {' '}
            <button
              className="doc-open-btn"
              onClick={() => onSelect?.({ documentId: doc._id })}
            >
              Open
            </button>
          </span>
        </li>
      ))}
    </ul>
  );
}
