// apps/web/src/lib/components/layout/SmartAccordion.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    items?: Record<string, unknown>[];
    idField?: string;
    triggerFields?: string[];
    selectedId?: string | null;
    onSelect?: (payload: { id: string | null }) => void;
    children?: Snippet;
  }

  let {
    items = [],
    idField = 'id',
    triggerFields = [],
    selectedId,
    onSelect,
    children,
  }: Props = $props();

  let openValue = $state<string>('');
  $effect(() => { if (typeof selectedId === 'string' && openValue === '') openValue = selectedId; });

  function getField(item: Record<string, unknown>, field: string): string {
    const val = item[field];
    if (val == null) return '';
    if (typeof val === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(val)) {
      return new Date(val).toLocaleString();
    }
    return String(val);
  }

  function toggle(id: string) {
    const next = openValue === id ? '' : id;
    openValue = next;
    onSelect?.({ id: next || null });
  }

  let isSelected = $derived((id: string) =>
    selectedId !== undefined ? selectedId === id && openValue === id : openValue === id
  );
</script>

{#if items.length === 0}
  <p class="text-muted-foreground text-xs">No entries found.</p>
{:else}
  <div class="accordion w-full">
    {#each items as item (String(item[idField] ?? ''))}
      {@const id = String(item[idField] ?? '')}
      {@const triggerText = (triggerFields as string[]).map((f) => getField(item, f)).filter(Boolean).join(' · ')}
      {@const open = openValue === id}
      <div class="accordion-item">
        <button
          class="accordion-trigger"
          onclick={() => toggle(id)}
          aria-expanded={open}
        >
          {triggerText || id}
          <span class="accordion-chevron" class:open>{open ? '▲' : '▼'}</span>
        </button>
        {#if open}
          <div class="accordion-content">
            {#if isSelected(id)}
              {@render children?.()}
            {:else}
              <p class="text-muted-foreground text-xs">Loading…</p>
            {/if}
          </div>
        {/if}
      </div>
    {/each}
  </div>
{/if}

<style>
  .accordion-item {
    border-bottom: 1px solid var(--border);
  }
  .accordion-trigger {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    padding: 0.75rem;
    background: none;
    border: none;
    text-align: left;
    font-size: 0.875rem;
    cursor: pointer;
  }
  .accordion-content {
    padding: 0.5rem 0.75rem 0.75rem;
  }
  .accordion-chevron {
    font-size: 0.6rem;
    color: var(--muted-foreground);
  }
</style>

// apps/web/src/components/layout/SmartAccordion.tsx
import { useState, ReactNode } from 'react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '../ui/accordion';

interface Props {
  items?: Record<string, unknown>[];
  idField?: string;
  triggerFields?: string[];
  selectedId?: string | null;
  onSelect?: (payload: { id: string | null }) => void;
  children?: ReactNode;
  [key: string]: unknown;
}

function getField(item: Record<string, unknown>, field: string): string {
  const val = item[field];
  if (val == null) return '';
  if (typeof val === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(val)) {
    return new Date(val).toLocaleString();
  }
  return String(val);
}

export function SmartAccordion({
  items = [],
  idField = 'id',
  triggerFields = [],
  selectedId,
  onSelect,
  children,
}: Props) {
  const [openValue, setOpenValue] = useState<string>('');

  const handleValueChange = (value: string) => {
    setOpenValue(value);
    onSelect?.({ id: value || null });
  };

  if (items.length === 0) {
    return <p className="text-muted-foreground text-xs">No entries found.</p>;
  }

  return (
    <Accordion
      type="single"
      collapsible
      value={openValue}
      onValueChange={handleValueChange}
      className="w-full"
    >
      {items.map((item) => {
        const id = String(item[idField] ?? '');
        const triggerText = triggerFields.map((f) => getField(item, f)).filter(Boolean).join(' · ');
        const isSelected = selectedId === id && openValue === id;

        return (
          <AccordionItem key={id} value={id}>
            <AccordionTrigger>{triggerText || id}</AccordionTrigger>
            <AccordionContent>
              {isSelected
                ? children
                : <p className="text-muted-foreground text-xs">Loading…</p>}
            </AccordionContent>
          </AccordionItem>
        );
      })}
    </Accordion>
  );
}
